name: ci

on:
  push:
    paths:
      - 'release-versions/mcsm-version-web.txt'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Get version
        id: ver
        run: echo "version=$(cat release-versions/mcsm-version-web.txt)" >> $GITHUB_OUTPUT
      -
        name: Get tags
        id: tag
        with:
          images: ph59x/mcsmanager-web
          tags: |
            type = raw, value = ${{ steps.ver.outputs.version }}
            type = raw, value = latest
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./daemon.dockerfile
          tags: ph59x/mcsmanager-web:latest